l = [
	"GAME_ACT_NONE",
	"GAME_ACT_UP",
	"GAME_ACT_RIGHT",
	"GAME_ACT_DOWN",
	"GAME_ACT_LEFT",
	"GAME_ACT_INTERACT",
	"GAME_ACT_CLOSE",
	"GAME_ACT_EDIT_UP",
	"GAME_ACT_EDIT_RIGHT",
	"GAME_ACT_EDIT_DOWN",
	"GAME_ACT_EDIT_LEFT",
	"GAME_ACT_EDIT_PLACE",
	"GAME_ACT_EDIT_REMOVE",
	"GAME_ACT_EDIT_FILL",
	"GAME_ACT_EDIT_EMPTY",
	"GAME_ACT_EDIT_SAVE",
]

for i in l:
	print(f"game.act.{i.replace('GAME_ACT_', '')} = {i}")
